### ISSUE TITLE
restas-doc doesn't build today

### ISSUE THREAD

**Issue by quicklisp** [archimag/restas#41]
I don't really understand it, but this is what I get:

    ; caught ERROR:
    ;   (during macroexpansion of (RESTAS:MOUNT-MODULE -HTML- ...))
    ;   The value-HTML-is not of typeLIST

More context at http://report.quicklisp.org/2016-06-22/failure-report/restas.html#restas-doc

**Comment by eadmund** [comment]
I'm getting a similar issue, which is breaking my code too.  It looks like 589d28d458d35931c015b4f48b8a8fcbaee8dc5f is to blame. I'm not certain what the intention of that commit is; will read up more later.

**Comment by eadmund** [comment]
I think maybe lines 274 & 275 in src/modules.lisp should be transposed?

https://github.com/archimag/restas/commit/589d28d458d35931c015b4f48b8a8fcbaee8dc5f#diff-9649abf2b862a54ba0b4756a053836a6L273

**Comment by alexey-martynov** [comment]
You're completely right.
