### ISSUE TITLE
compilation error in example

### ISSUE THREAD

**Issue by cage2** [archimag/restas#42]
Hi!

seems that I am getting some trouble compiling 

https://github.com/archimag/restas/blob/master/example/example-1.lisp

sbcl (version 1.3.3 on debian if that matters)

the error is 
The value RESTAS.PUBLISH-RST::-RAW- is not of type LIST.
  [Condition of type TYPE-ERROR]

maybe something wrong here?
https://github.com/archimag/restas/blob/1e52748a43c642fc43750fe26a727d9ab6c77653/src/declarations.lisp#L112

**Comment by alexey-martynov** [comment]
I can't reproduce this on Clozure CL. I'l try on SBCL tomorrow.

Are you sure about this sample? There is and issue #41 with mounting modules so it might be another example?

**Comment by cage2** [comment]
Oh, me stupid! 

I did not checked the issue's list, yes this is the same as #41 and moreover the example file was not the correct one (i meant https://github.com/archimag/restas/blob/master/example/publish-rst.lisp).

Just checked with last commit and the bug is gone.

Thank you for your reply and the quick fix! :)
C.
