### ISSUE TITLE
Possibly confusing handling of default values in define-policy

### ISSUE THREAD

**Issue by christophejunke** [archimag/restas#49]
When calling `define-policy`, the keyword arguments in `%define-policy` that were absent in `define-policy` are set to NIL, and do not take their default values. This can lead to errors when the NIL value is not meaningful for that option, as described in this question: https://stackoverflow.com/q/58257183/124319

There are different fixes possible, that basically boils down to handling NIL values in `%define-policy` or preventing the `define-policy` macro from giving keyword arguments when they are nil. I am not submitting a patch at the moment because I am not sure about which way seems better for you.

**Comment by archimag** [comment]
Sorry, I didn't use this code for years and I don't have any opinion about the best way. But I believe that people who needs can make  worth choice. So if you will make a path I will accept it and your choice about the best way to solve this problem.

**Comment by christophejunke** [comment]
Thank you
